package com.uaefts.portal.controller;

import java.net.http.HttpHeaders;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;

import com.uaefts.portal.service.FileProcessingService;
import com.uaefts.portal.service.TransactionServiceDao;

import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;


@RestController
@RequestMapping("/api/transactions")
public class FileProcessingController {
	

	@Autowired
	private TransactionServiceDao transaction;
	
	 @Autowired
	 private FileProcessingService fileProcessingService;
	
	@PutMapping("/update/{id}")
	public ResponseEntity<String> updateTransaction(@PathVariable Long id, @RequestParam String refNo) {
		//TODO: process PUT request
		
		String response= transaction.updateTransaction(id, refNo);
		return ResponseEntity.ok(response);
	}

	@GetMapping("/hello")
	public String hello() {
		
		return "hello";
	}
	
	@GetMapping("/call")
	public void readFile() {
		
		/*
		 * Path
		 * filePath=Paths.get("C://UAEFTS//incoming//E026033C1021022406270000077.FTR");
		 * try { byte[] fileContent=Files.readAllBytes(filePath);
		 * System.out.println("content---"+fileContent.length); } catch (Exception e) {
		 * System.out.println("exception"); e.printStackTrace(); }
		 */
		
		fileProcessingService.monitorDirectory();
	}
	
	
	@GetMapping("/getAccountDetails")
	public ResponseEntity<String> getAccount() {
		
		String json=getAccountDetails();
		org.springframework.http.HttpHeaders header=new org.springframework.http.HttpHeaders();
		return new ResponseEntity<>(json,header,HttpStatus.OK);
	}

	@PostMapping("/fundTransfer")
	public ResponseEntity<String> fundTransfer() {
		String json="{\r\n"
				+ "    \"msgId\": \"P4272851 246 1\",\r\n"
				+ "    \"trackingId\": \"2903078a-6b4a-11ef-bf75-ac18ae0f0000\",\r\n"
				+ "    \"status\": \"Success\",\r\n"
				+ "    \"transactionRefNo\": \"001ICLB242490003\"\r\n"
				+ "}\r\n"
				+ "";
		org.springframework.http.HttpHeaders header=new org.springframework.http.HttpHeaders();
		return new ResponseEntity<>(json,header,HttpStatus.OK);
	}
	
	@PostMapping("/getCustomerDetails")
	public ResponseEntity<String> getCustomerDetails() {
		
		String json=getCustomerDetals();
		org.springframework.http.HttpHeaders header=new org.springframework.http.HttpHeaders();
		return new ResponseEntity<>(json,header,HttpStatus.OK);
	}

	
	
	private String getCustomerDetals() {
		// TODO Auto-generated method stub
		String json="{\r\n"
				+ "    \"customerName\": \"TEST_CUSTOMER_010837357\",\r\n"
				+ "    \"cifId\": \"010837357\",\r\n"
				+ "    \"address\": \"TEST_CUSTOMER_010837357\",\r\n"
				+ "    \"addressLine2\": \"TEST_CUSTOMER_010837357\",\r\n"
				+ "    \"addressLine3\": \"TEST_CUSTOMER_010837357\",\r\n"
				+ "    \"addressLine4\": \"AE\",\r\n"
				+ "    \"country\": \"AE\",\r\n"
				+ "    \"nationality\": \"EG\",\r\n"
				+ "    \"language\": \"ENG\",\r\n"
				+ "    \"expcntry\": \"AE\",\r\n"
				+ "    \"uidName\": \"PASSPORT\",\r\n"
				+ "    \"uidValue\": \"010837357\",\r\n"
				+ "    \"location\": \"21\",\r\n"
				+ "    \"frozen\": \"N\",\r\n"
				+ "    \"dead\": \"N\",\r\n"
				+ "    \"whrunkn\": \"N\",\r\n"
				+ "    \"chargeGroup\": \"GOLD\",\r\n"
				+ "    \"ccateg\": \"CUSTGOLD\",\r\n"
				+ "    \"fxnettcust\": \"010837357\",\r\n"
				+ "    \"xRef\": \"25065598\",\r\n"
				+ "    \"media\": \"MAIL\",\r\n"
				+ "    \"mailrsreqd\": \"N\",\r\n"
				+ "    \"clsParticipant\": \"N\",\r\n"
				+ "    \"crmCustomer\": \"N\",\r\n"
				+ "    \"issuCustomer\": \"N\",\r\n"
				+ "    \"trsryCustomer\": \"N\",\r\n"
				+ "    \"sName\": \"TEST_CUST_010837357\",\r\n"
				+ "    \"lBranch\": \"025\",\r\n"
				+ "    \"customerType\": \"I\",\r\n"
				+ "    \"flgJoint\": \"\",\r\n"
				+ "    \"fullName\": \"TEST_CUSTOMER_010837357\",\r\n"
				+ "    \"amlReqD\": \"N\",\r\n"
				+ "    \"flgutltyprvdr\": \"N\",\r\n"
				+ "    \"chkdigitvalreqd\": \"N\",\r\n"
				+ "    \"constaxcertrqd\": \"N\",\r\n"
				+ "    \"indtaxcertrqd\": \"N\",\r\n"
				+ "    \"ftaccasof\": \"D\",\r\n"
				+ "    \"emailUDF5\": \"abc@xyz.com\",\r\n"
				+ "    \"udfLabel1\": \"010837357\",\r\n"
				+ "    \"fxcustclrilim\": \"0\",\r\n"
				+ "    \"overLimit\": \"0\",\r\n"
				+ "    \"fxCleanRisk\": \"0\",\r\n"
				+ "    \"limCCY\": \"AED\",\r\n"
				+ "    \"seccustclrilim\": \"0\",\r\n"
				+ "    \"secclrilim\": \"0\",\r\n"
				+ "    \"seccustpsrilim\": \"0\",\r\n"
				+ "    \"secpsrilim\": \"0\",\r\n"
				+ "    \"custunadv\": \"N\",\r\n"
				+ "    \"clsccyallwd\": \"D\",\r\n"
				+ "    \"mt920\": \"N\",\r\n"
				+ "    \"relpricing\": \"Y\",\r\n"
				+ "    \"kycStatus\": \"V\",\r\n"
				+ "    \"sStaff\": \"N\",\r\n"
				+ "    \"kycReferenceNumber\": \"025ZKYC123150168\",\r\n"
				+ "    \"jointVenture\": \"N\",\r\n"
				+ "    \"privateCustomer\": \"N\",\r\n"
				+ "    \"blackList\": \"N\",\r\n"
				+ "    \"mailDelOpt\": \"N\",\r\n"
				+ "    \"salCreditCustomer\": \"N\",\r\n"
				+ "    \"swiftCopyInAdvice\": \"Y\",\r\n"
				+ "    \"crc\": \"Y\",\r\n"
				+ "    \"dedupeCom\": \"N\",\r\n"
				+ "    \"dedupeRequied\": \"N\",\r\n"
				+ "    \"dormintimationRequied\": \"Y\",\r\n"
				+ "    \"orderCustomer\": \"0000\",\r\n"
				+ "    \"bussinessCode\": \"901\",\r\n"
				+ "    \"purposeCode\": \"969\",\r\n"
				+ "    \"crRestructApplied\": \"N\",\r\n"
				+ "    \"dormant\": \"Y\",\r\n"
				+ "    \"autoCustomerAccount\": \"N\",\r\n"
				+ "    \"autoKYC\": \"N\",\r\n"
				+ "    \"identityExpiryDate\": \"2020-08-21\",\r\n"
				+ "    \"underFormation\": \"N\",\r\n"
				+ "    \"skipSegmentUpdate\": \"Y\",\r\n"
				+ "    \"mailrCount\": \"2\",\r\n"
				+ "    \"fatcanotapp1\": \"N\",\r\n"
				+ "    \"privateGoldCustomerResponse1\": \"Y\",\r\n"
				+ "    \"enameCheckDate\": \"2016-08-27\",\r\n"
				+ "    \"enameCheck\": \"N\",\r\n"
				+ "    \"allowVirtualAccounts\": \"N\",\r\n"
				+ "    \"kycRequied\": \"N\",\r\n"
				+ "    \"mashreqMatrix\": \"N\",\r\n"
				+ "    \"consoleDepositCharge\": \"N\",\r\n"
				+ "    \"autoCRS\": \"N\",\r\n"
				+ "    \"flexiProcessCustomer\": \"N\",\r\n"
				+ "    \"flexiProcessExep\": \"N\",\r\n"
				+ "    \"cifCreationDate\": \"2012-03-18\",\r\n"
				+ "    \"maker\": \"106434\",\r\n"
				+ "    \"makerStamp\": \"2018-10-06 10:44:04\",\r\n"
				+ "    \"checker\": \"105845\",\r\n"
				+ "    \"checkerStamp\": \"2018-10-06 12:40:01\",\r\n"
				+ "    \"modNumber\": \"7\",\r\n"
				+ "    \"transactionStatus\": \"O\",\r\n"
				+ "    \"authorizationStatus\": \"A\",\r\n"
				+ "    \"relationshipManager\": \"0\",\r\n"
				+ "    \"rmName\": \"No Relationship Manager Assigned\",\r\n"
				+ "    \"express\": \"N\",\r\n"
				+ "    \"custPersonal\": {\r\n"
				+ "        \"firstName\": \"TEST_CUSTOMER_010837357\",\r\n"
				+ "        \"dob\": \"1958-10-09\",\r\n"
				+ "        \"minor\": \"N\",\r\n"
				+ "        \"sex\": \"M\",\r\n"
				+ "        \"nationId\": \"010837357\",\r\n"
				+ "        \"passportNo\": \"010837357\",\r\n"
				+ "        \"passportIssueDate\": \"2013-08-22\",\r\n"
				+ "        \"passportExpiryDate\": \"2020-08-21\",\r\n"
				+ "        \"dAddress1\": \"TEST_CUSTOMER_010837357\",\r\n"
				+ "        \"dAddress2\": \"TEST_CUSTOMER_010837357\",\r\n"
				+ "        \"dAddress3\": \"TEST_CUSTOMER_010837357\",\r\n"
				+ "        \"telephone\": \"010837357\",\r\n"
				+ "        \"fax\": \"010837357\",\r\n"
				+ "        \"email\": \"abc@xyz.com\",\r\n"
				+ "        \"pAddress1\": \"TEST_CUSTOMER_010837357\",\r\n"
				+ "        \"pAddress2\": \"TEST_CUSTOMER_010837357\",\r\n"
				+ "        \"pAddress3\": \"TEST_CUSTOMER_010837357\",\r\n"
				+ "        \"dcntry\": \"AE\",\r\n"
				+ "        \"pcntry\": \"EG\",\r\n"
				+ "        \"resStatus\": \"R\",\r\n"
				+ "        \"mobileNumber\": \"0501234567\",\r\n"
				+ "        \"sbmtageProof\": \"V\",\r\n"
				+ "        \"customerCommMode\": \"M\",\r\n"
				+ "        \"visaNumber\": \"010837357\",\r\n"
				+ "        \"visaExpiryDate\": \"2017-06-17\",\r\n"
				+ "        \"address5\": \"010837357\",\r\n"
				+ "        \"pptIssuePlace\": \"EGYPT\",\r\n"
				+ "        \"placeOfBirth\": \"EG\",\r\n"
				+ "        \"guardian\": \"EG\",\r\n"
				+ "        \"visaIssueDate\": \"2014-06-18\",\r\n"
				+ "        \"visaIssuePlace\": \"DUBAI\",\r\n"
				+ "        \"custDomestic\": {\r\n"
				+ "            \"eduStatus\": \"N\",\r\n"
				+ "            \"maritalStatus\": \"M\",\r\n"
				+ "            \"spempStatus\": \"O\",\r\n"
				+ "            \"depChild\": \"0\",\r\n"
				+ "            \"accomoDate\": \"O\",\r\n"
				+ "            \"customerNumber\": \"010837357\",\r\n"
				+ "            \"deptOth\": \"0\"\r\n"
				+ "        },\r\n"
				+ "        \"custprof\": {\r\n"
				+ "            \"empStatus\": \"S\",\r\n"
				+ "            \"currentDesignation\": \"PARTNER\",\r\n"
				+ "            \"currentEmp\": \"18\",\r\n"
				+ "            \"orgName\": \"TEST_CUSTOMER_010837357\",\r\n"
				+ "            \"department\": \"TEST_CUSTOMER_010837357\",\r\n"
				+ "            \"pobox\": \"TEST_CUSTOMER_010837357\",\r\n"
				+ "            \"tel\": \"010837357\",\r\n"
				+ "            \"fax\": \"010837357\",\r\n"
				+ "            \"email\": \"worldtranscairo@gmail.com\",\r\n"
				+ "            \"salary\": \"0\",\r\n"
				+ "            \"others1\": \"0\",\r\n"
				+ "            \"amountCurrency1\": \"AED\",\r\n"
				+ "            \"customerNumber\": \"010837357\",\r\n"
				+ "            \"employerDescription\": \"OTHERS\",\r\n"
				+ "            \"city\": \"DUBAI,UNITED ARAB EMIRATES\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    \"custCorp\": {\r\n"
				+ "        \"screening\": \"N\",\r\n"
				+ "        \"custCorpDir\": []\r\n"
				+ "    },\r\n"
				+ "    \"custFatcaInd\": {\r\n"
				+ "        \"custNoCtRefNo\": \"010837357\",\r\n"
				+ "        \"sequenceNumber\": \"1\",\r\n"
				+ "        \"module\": \"STDCIF\",\r\n"
				+ "        \"customerType\": \"I\",\r\n"
				+ "        \"alternativeNationality\": \"EG\",\r\n"
				+ "        \"countryOfBirth\": \"EG\",\r\n"
				+ "        \"parentCoCountryOfIncor\": \"EG\",\r\n"
				+ "        \"usTaxPayer\": \"N\",\r\n"
				+ "        \"usResWithUsMailAddOrPo\": \"N\",\r\n"
				+ "        \"ownerUsTelePhoneNumber\": \"N\",\r\n"
				+ "        \"ownerUsPhoneNumber\": \"+001-\",\r\n"
				+ "        \"ownerUsProperty\": \"N\",\r\n"
				+ "        \"incareOfOrHoldmailAddUs\": \"N\",\r\n"
				+ "        \"poaOrSignAuthWithAddUs\": \"N\",\r\n"
				+ "        \"usGreenCardHolder\": \"N\",\r\n"
				+ "        \"usSocialSecurityHolder\": \"N\",\r\n"
				+ "        \"standingInstUsBeneficiary\": \"N\",\r\n"
				+ "        \"busIncDerivedTradeBusus\": \"N\",\r\n"
				+ "        \"usOwnerExceed10PctHolding\": \"N\",\r\n"
				+ "        \"accountClassification\": \"NONUS\",\r\n"
				+ "        \"w8w9Receipt\": \"N\",\r\n"
				+ "        \"declarationDocument\": \"N\",\r\n"
				+ "        \"bankingSecurityWaiver\": \"N\",\r\n"
				+ "        \"permissionToReport\": \"N\",\r\n"
				+ "        \"ffi\": \"N\",\r\n"
				+ "        \"npffi\": \"N\",\r\n"
				+ "        \"giinValidationWithIrs\": \"N\",\r\n"
				+ "        \"usbasedfi\": \"N\"\r\n"
				+ "    },\r\n"
				+ "    \"custJoint\": {},\r\n"
				+ "    \"custTax\": [],\r\n"
				+ "    \"udfDetails\": [\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ACTIVE_AUTHORIZEDIDENTITY_DATE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"AC_CORP_TYPE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"AC_INTERMEDIARY_NAME\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"AC_LEAD_CIF\",\r\n"
				+ "            \"fieldValue\": \"010837357\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"AC_MGMT\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"AC_OTHER_RELATION\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"AC_SOURCE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"AC_SOURCE_OTHERS\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"AC_TYPE_OTHERS\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ADDRESS_PROOF\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ADD_PRODUCTS\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"APPLICATION_SCORE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"APP_EADD\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"APP_EXPL\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"APP_LGDD\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"APP_MRS\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"APP_PBDF\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"APP_SCORE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ASST_RELATION_MANAGER\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ASST_RM_NAME\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"AYAAN_CUSTOMER\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BALANCE_SHEET_DATE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BDMANAGER\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BEHAVIOR_SCORE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BEH_EADD\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BEH_EXPL\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BEH_HISTMRS\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BEH_LGDD\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BEH_MRRS\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BEH_PBDF\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BEH_SCORE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BHID_EXP\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BLACK_LISTED\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BLACK_LIST_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BORROWER_TYPE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BORROWING_CLIENT\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BUSINESS_GROUP\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CAPITAL_INVEST_AMT\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CASH_MANAGEMENT_CUSTOMER\",\r\n"
				+ "            \"fieldValue\": \"N\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CBK_NO\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CB_CATEG\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CHANNEL_INDEMNITY\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CIBG_BUSINESS_GROUP\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CIF_FAX_NUMBER\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CIF_TYPE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CINO\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"COMDELDSC\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"COMMERCIAL_ACTIVITY\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"COMPRISKCD\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CONSENT\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CONSENT_DATE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CORP_CUSTOMER\",\r\n"
				+ "            \"fieldValue\": \"NOTCORPCUST\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"COST_CENTER\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CREDIT_MANAGER\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CSNO\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CUST_DEPARTMENT\",\r\n"
				+ "            \"fieldValue\": \"OTHERS\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"DEFAULT_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"DO_NOT_CALL\",\r\n"
				+ "            \"fieldValue\": \"01\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"DT_OF_LEGAL_ACTION\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"E-STATEMENT_REQD\",\r\n"
				+ "            \"fieldValue\": \"Yes\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"EADD\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ECONOMIC_ACTIVITY_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"EDD_FLAG\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ELCM_EL\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ELCM_LGD\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ELCM_PD\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"EMAIL_ID2\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"EMIRATES_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"EMPLOYEE_ID\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"EMPLOYMENT_DATE\",\r\n"
				+ "            \"fieldValue\": \"14-JUL-08\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ENGAGEMENT_SCORE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ESTMT_ALERT_FLAG\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"EXPL\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"FAX_INDEMNITY_FLAG\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"FCRR\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"GROUP_ID\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"IDENTITY_EXP_DATE\",\r\n"
				+ "            \"fieldValue\": \"10-JAN-14\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ILLITERATE_FLAG\",\r\n"
				+ "            \"fieldValue\": \"N\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"IMA_FLAG\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"IMMIGRATION_NO\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"INTROACNO\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"INTRODUCER_NAME\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"INV_COOLING_OFF_DATE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"IN_RISK_RATING\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"IN_RISK_RATING_OPTION\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"IN_RISK_UPD_DT\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ISSUER_TYPE_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"KYC_LAST_REVIEW_DATE_OLD\",\r\n"
				+ "            \"fieldValue\": \"16-AUG-16\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"KYC_NEXT_REVIEW_DATE_OLD\",\r\n"
				+ "            \"fieldValue\": \"16-AUG-21\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"LEGAL_ACTION_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"LEGAL_ACTION_CODES\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"LGDD\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"LICENCING_AUTHORITY\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"LOBCODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"MASHREQ_CUSTOMER\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"MM_NEWS_SUBSCRIPTION\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"MOBILE_NO2\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"MRRS\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"MRS12\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"OFFSHORE_CIF\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"OFF_EXTN_NO\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ONBOARDING_PARTNER\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"OVERSEAS_MOBILE_NUMBER\",\r\n"
				+ "            \"fieldValue\": \"201223158893\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PBDF\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PRIMARY_BANK\",\r\n"
				+ "            \"fieldValue\": \"N\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PRIORITY_FLAG\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PROFESSION_CD\",\r\n"
				+ "            \"fieldValue\": \"47\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PROMO_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PVTGLD_ARM_EMAIL_ID\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PVTGLD_ARM_TELEPHONE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PVTGLD_CLIENT_TYP\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PVTGLD_IA_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PVTGLD_IA_EMAIL_ID\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PVTGLD_IA_NAME\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PVTGLD_IA_TELEPHONE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PVTGLD_RM_EMAIL_ID\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PVTGLD_SUBSEGMNT\",\r\n"
				+ "            \"fieldValue\": \"Not_Qualified\\n\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PVTGLD_UNIT_MANAGER_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PVTGLD_UNIT_MANAGER_EMAIL\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PVTGLD_UNIT_MANAGER_NAME\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PVTGLD_UNIT_MANAGER_TELEPHONE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PVTWLT_RM_ARM_VRM\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"REASON_WAIVE_REL_FEE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"REF_CIF\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"RELATIONSHIP_FEE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"RELATIONSHIP_MANAGER\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"RELATION_OFFICER\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"RISK_RATING\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"RM_ADDRESS_1\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"RM_ADDRESS_2\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"RM_CONTACT_NO\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ROYAL_FAMILY\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"RUNNERLOGINID\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"RUNNERSTAFFID\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"SCHEDULE_OF_CHARGES\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"SCORE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"SEC_NUM\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"SIC_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"SKIP_FLAG\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"SKIP_FLAG_DATE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"SMS_ALERT\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"SOURCELEAD_BC\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"SPONSOR_NAME\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"SSN_EXP_DATE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"SUB_COMPANY_TYPE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"SUB_SIC_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"TELEPHONE_INDEMNITY\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"TESS_CATEGORY\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"TESS_EFFECTIVE_DATE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"TESS_SUPPORT_TYPE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"TL_ISSUING_AUTHORITY\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"UDA_FLAG\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"UNDER_FORM_CMPY\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"UNIQUE_NAME\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"VISA_EXP_DATE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"WAIVER_FLAG\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"WAIVE_REL_FEE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"WRM_NAME\"\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"custAccDet\": {\r\n"
				+ "        \"relationshipLinkage\": [\r\n"
				+ "            {\r\n"
				+ "                \"customer\": \"010837357\",\r\n"
				+ "                \"relationship\": \"PRIMARY\",\r\n"
				+ "                \"inherit\": \"N\",\r\n"
				+ "                \"descp\": \"TEST_CUSTOMER_010837357\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"customer\": \"010854092\",\r\n"
				+ "                \"relationship\": \"NOTGIVEN\",\r\n"
				+ "                \"inherit\": \"N\",\r\n"
				+ "                \"descp\": \"TEST_CUSTOMER_010854092\"\r\n"
				+ "            }\r\n"
				+ "        ]\r\n"
				+ "    },\r\n"
				+ "    \"zohoDetails\": {},\r\n"
				+ "    \"custmis\": {\r\n"
				+ "        \"customer\": \"010837357\",\r\n"
				+ "        \"branchId\": \"025\",\r\n"
				+ "        \"custchnglog\": [\r\n"
				+ "            {\r\n"
				+ "                \"misCls\": \"CUST_SGMT\",\r\n"
				+ "                \"txnDt\": \"2015-01-07\",\r\n"
				+ "                \"oldMisCd\": \"CSS0011\",\r\n"
				+ "                \"newMisCd\": \"CSS0010\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"misCls\": \"CUST_SGMT\",\r\n"
				+ "                \"txnDt\": \"2015-02-16\",\r\n"
				+ "                \"oldMisCd\": \"CSS0010\",\r\n"
				+ "                \"newMisCd\": \"CSS0030\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"misCls\": \"CUST_SGMT\",\r\n"
				+ "                \"txnDt\": \"2015-08-31\",\r\n"
				+ "                \"oldMisCd\": \"CSS0030\",\r\n"
				+ "                \"newMisCd\": \"CSS0010\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"dfltcd\": [\r\n"
				+ "            {\r\n"
				+ "                \"misCls\": \"INDUSTRY\",\r\n"
				+ "                \"misCd\": \"IND0021\",\r\n"
				+ "                \"misDescription\": \"Personal\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"misCls\": \"SEGMENT\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"dfltcda\": [\r\n"
				+ "            {\r\n"
				+ "                \"misCls\": \"BUS_GRP\",\r\n"
				+ "                \"misCd\": \"RBG\",\r\n"
				+ "                \"misDescription\": \"Retail Banking Group\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"misCls\": \"CUST_SGMT\",\r\n"
				+ "                \"misCd\": \"CSS0010\",\r\n"
				+ "                \"misDescription\": \"mashreq Gold\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"misCls\": \"GEOGRAPHY\",\r\n"
				+ "                \"misCd\": \"A3\",\r\n"
				+ "                \"misDescription\": \"United Arab Emirates - Dubai\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"misCls\": \"SRC_BRN\",\r\n"
				+ "                \"misCd\": \"SCH0001\",\r\n"
				+ "                \"misDescription\": \"Branch\"\r\n"
				+ "            }\r\n"
				+ "        ]\r\n"
				+ "    },\r\n"
				+ "    \"custAcDetails\": {\r\n"
				+ "        \"custText\": [\r\n"
				+ "            {\r\n"
				+ "                \"sequenceNumber\": \"1\",\r\n"
				+ "                \"userId\": \"105845\",\r\n"
				+ "                \"instructionDate\": \"2016-08-27\",\r\n"
				+ "                \"description\": \"KYC and SALARY details has been updated as per 'Calling KYC Project' form received on 16-08-2016\\n\",\r\n"
				+ "                \"authorizationStatus\": \"A\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"sequenceNumber\": \"2\",\r\n"
				+ "                \"userId\": \"106187\",\r\n"
				+ "                \"instructionDate\": \"2018-10-04\",\r\n"
				+ "                \"description\": \"AS PER EDMS-888322 NO DEBIT FOR COMPLAICNE REMOVED\",\r\n"
				+ "                \"authorizationStatus\": \"A\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"sequenceNumber\": \"3\",\r\n"
				+ "                \"userId\": \"106434\",\r\n"
				+ "                \"instructionDate\": \"2018-10-06\",\r\n"
				+ "                \"description\": \"ACCOUNT 010794719542 CLOSED UNDER THE EDMS 88832\\n REASON: NO NEED \",\r\n"
				+ "                \"authorizationStatus\": \"A\"\r\n"
				+ "            }\r\n"
				+ "        ]\r\n"
				+ "    },\r\n"
				+ "    \"custDocCheckList\": []\r\n"
				+ "}";
		
		return json;
	}

	private String getAccountDetails() {
		String json="{\r\n"
				+ "    \"branch\": \"017\",\r\n"
				+ "    \"accountNo\": \"010693206884\",\r\n"
				+ "    \"cifId\": \"010022848\",\r\n"
				+ "    \"accCls\": \"CUGOLD\",\r\n"
				+ "    \"accountCurrency\": \"AED\",\r\n"
				+ "    \"customerName\": \"TEST_CUSTOMER_010022848\",\r\n"
				+ "    \"accountDescription\": \"TEST_ACCOUNT_010022848\",\r\n"
				+ "    \"accountClsType\": \"U\",\r\n"
				+ "    \"noOfDebits\": \"N\",\r\n"
				+ "    \"noOfCredits\": \"N\",\r\n"
				+ "    \"stopPayments\": \"N\",\r\n"
				+ "    \"isDormant\": \"N\",\r\n"
				+ "    \"accountType\": \"S\",\r\n"
				+ "    \"accountOpenDate\": \"1995-01-04\",\r\n"
				+ "    \"altAccount\": \"0693206884\",\r\n"
				+ "    \"isBlocked\": \"N\",\r\n"
				+ "    \"organization\": \"TEST_ACCOUNT_010022848\",\r\n"
				+ "    \"department\": \"TEST_ACCOUNT_010022848\",\r\n"
				+ "    \"poBox\": \"TEST_ACCOUNT_010022848\",\r\n"
				+ "    \"postingAllowed\": \"Y\",\r\n"
				+ "    \"ibanAccountNumber\": \"AE020330000010693206884\",\r\n"
				+ "    \"trackReceivable\": \"Y\",\r\n"
				+ "    \"refReq\": \"N\",\r\n"
				+ "    \"accStat\": \"NORM\",\r\n"
				+ "    \"txnStat\": \"O\",\r\n"
				+ "    \"statusSince\": \"1995-01-04\",\r\n"
				+ "    \"propagateReportFlag\": \"Y\",\r\n"
				+ "    \"dormprm\": \"M\",\r\n"
				+ "    \"custLocation\": \"00\",\r\n"
				+ "    \"media\": \"MAIL\",\r\n"
				+ "    \"goldCustomer\": \"Y\",\r\n"
				+ "    \"chequeBook\": \"Y\",\r\n"
				+ "    \"passBook\": \"N\",\r\n"
				+ "    \"casaAccount\": \"N\",\r\n"
				+ "    \"atmAccount\": \"010693206884\",\r\n"
				+ "    \"modNo\": \"6\",\r\n"
				+ "    \"mt210Reqd\": \"N\",\r\n"
				+ "    \"chequeBookName1\": \"TEST_ACCOUNT_010022848\",\r\n"
				+ "    \"chequeBookName2\": \"TEST_ACCOUNT_010022848\",\r\n"
				+ "    \"autoReOrderChkReq\": \"N\",\r\n"
				+ "    \"lodgebkfac\": \"N\",\r\n"
				+ "    \"allwbkperentry\": \"Y\",\r\n"
				+ "    \"autoProvReq\": \"N\",\r\n"
				+ "    \"provccyype\": \"L\",\r\n"
				+ "    \"defrecon\": \"N\",\r\n"
				+ "    \"consreqd\": \"N\",\r\n"
				+ "    \"funding\": \"N\",\r\n"
				+ "    \"ibanRqd\": \"Y\",\r\n"
				+ "    \"lmtCurrency\": \"AED\",\r\n"
				+ "    \"statementDay\": \"20\",\r\n"
				+ "    \"statementFrequency\": \"M\",\r\n"
				+ "    \"atmFlag\": \"Y\",\r\n"
				+ "    \"accStmtType\": \"D\",\r\n"
				+ "    \"accStmtType2\": \"N\",\r\n"
				+ "    \"accStmtType3\": \"N\",\r\n"
				+ "    \"flgExclrvrtrans\": \"N\",\r\n"
				+ "    \"swpType\": \"1\",\r\n"
				+ "    \"regdApp\": \"N\",\r\n"
				+ "    \"regdper\": \"N\",\r\n"
				+ "    \"prdlst\": \"D\",\r\n"
				+ "    \"txnlst\": \"D\",\r\n"
				+ "    \"spcondlst\": \"N\",\r\n"
				+ "    \"spocndtxn\": \"N\",\r\n"
				+ "    \"autoStatChange\": \"N\",\r\n"
				+ "    \"odReq\": \"Y\",\r\n"
				+ "    \"authStatus\": \"A\",\r\n"
				+ "    \"checkerStamp\": \"2023-01-09 03:08:49\",\r\n"
				+ "    \"checker\": \"SCHEDULER\",\r\n"
				+ "    \"maker\": \"SCHEDULER\",\r\n"
				+ "    \"makerStamp\": \"2023-01-09 03:08:46\",\r\n"
				+ "    \"acstcls\": \"N\",\r\n"
				+ "    \"skipKYCIdExp\": \"N\",\r\n"
				+ "    \"screening\": \"N\",\r\n"
				+ "    \"fundSharing\": \"N\",\r\n"
				+ "    \"relationMgrCode\": \"45888\",\r\n"
				+ "    \"projAcc\": \"N\",\r\n"
				+ "    \"salaryAccount\": \"Y\",\r\n"
				+ "    \"waiveAccOpenChrg\": \"N\",\r\n"
				+ "    \"maxNoChqRej\": \"3\",\r\n"
				+ "    \"noDebitForKycExpr\": \"N\",\r\n"
				+ "    \"mailDeliveryOption\": \"O\",\r\n"
				+ "    \"businessCode\": \"901\",\r\n"
				+ "    \"purposeCode\": \"969\",\r\n"
				+ "    \"noDebitForKYCExpr\": \"N\",\r\n"
				+ "    \"noOfReturnCheques\": \"1\",\r\n"
				+ "    \"deliveryMode\": \"C\",\r\n"
				+ "    \"salesOffCode\": \"0\",\r\n"
				+ "    \"relOffName\": \"Rahul Gajri \",\r\n"
				+ "    \"swiftCopyAdvChg\": \"Y\",\r\n"
				+ "    \"pvtCustApply\": \"N\",\r\n"
				+ "    \"echqYn\": \"N\",\r\n"
				+ "    \"manualTrackedFunds\": \"N\",\r\n"
				+ "    \"initFundStatus\": \"Y\",\r\n"
				+ "    \"rdyCrd\": \"N\",\r\n"
				+ "    \"autoAllocateTod\": \"N\",\r\n"
				+ "    \"forcePost\": \"N\",\r\n"
				+ "    \"replyCustSig\": \"N\",\r\n"
				+ "    \"intDetails\": {\r\n"
				+ "        \"calcAcc\": \"010693206884\",\r\n"
				+ "        \"bookAcc\": \"010693206884\",\r\n"
				+ "        \"intStartDt\": \"2023-01-09\",\r\n"
				+ "        \"bookAccBrn\": \"017\",\r\n"
				+ "        \"chgBookAccBrn\": \"017\",\r\n"
				+ "        \"chgBookAcc\": \"010693206884\",\r\n"
				+ "        \"chgStartDt\": \"2023-01-06\"\r\n"
				+ "    },\r\n"
				+ "    \"amountDates\": {\r\n"
				+ "        \"drIntproDue\": \"0\",\r\n"
				+ "        \"provAmt\": \"0\",\r\n"
				+ "        \"chgDue\": \"0\",\r\n"
				+ "        \"acyUnauthTankdr\": \"0\",\r\n"
				+ "        \"acyUnauthTankcr\": \"0\",\r\n"
				+ "        \"limitAmount\": \"0\",\r\n"
				+ "        \"withdraeableUncolledFund\": \"0\",\r\n"
				+ "        \"acyOpeningBal\": \"630855.87\",\r\n"
				+ "        \"lcyOpeningBal\": \"630855.87\",\r\n"
				+ "        \"acyTodayToverDr\": \"0\",\r\n"
				+ "        \"lcyTodayToverDr\": \"0\",\r\n"
				+ "        \"acyTodayToverCr\": \"0\",\r\n"
				+ "        \"lcyTodayToverCr\": \"0\",\r\n"
				+ "        \"acyTankCr\": \"0\",\r\n"
				+ "        \"acyTankDr\": \"0\",\r\n"
				+ "        \"lcyTankCr\": \"0\",\r\n"
				+ "        \"lcyTankDr\": \"0\",\r\n"
				+ "        \"acyTankUncollected\": \"0\",\r\n"
				+ "        \"acyCurrBalance\": \"630855.87\",\r\n"
				+ "        \"lcyCurrBalance\": \"630855.87\",\r\n"
				+ "        \"acyBlockedAmount\": \"0\",\r\n"
				+ "        \"acyAvlBal\": \"630855.87\",\r\n"
				+ "        \"acyUnauthDr\": \"0\",\r\n"
				+ "        \"acyUnauthTankDr\": \"0\",\r\n"
				+ "        \"acyUnauthCr\": \"0\",\r\n"
				+ "        \"acyUnauthTankCr\": \"0\",\r\n"
				+ "        \"acyUnauthUncollected\": \"0\",\r\n"
				+ "        \"acyUnauthTankUncollected\": \"0\",\r\n"
				+ "        \"accAccruedDrIc\": \"0\",\r\n"
				+ "        \"accAccruedCrIc\": \"0\",\r\n"
				+ "        \"dateLastCrActivity\": \"2023-12-21\",\r\n"
				+ "        \"dateLastDrActivity\": \"2023-12-20\",\r\n"
				+ "        \"dateLastDr\": \"2023-12-20\",\r\n"
				+ "        \"dateLastCr\": \"2023-12-21\",\r\n"
				+ "        \"acyUncollected\": \"0\",\r\n"
				+ "        \"receivableAmount\": \"0\",\r\n"
				+ "        \"dcLcyOpenBal\": \"Cr\",\r\n"
				+ "        \"disUnutilizedAmount\": \"0\",\r\n"
				+ "        \"disTotAvlAmount\": \"630855.87\",\r\n"
				+ "        \"UnutilizedAmount\": \"0\",\r\n"
				+ "        \"sweepEligBal\": \"630855.87\",\r\n"
				+ "        \"lastDebit\": \"425.65\",\r\n"
				+ "        \"lastCredit\": \"47325.4\",\r\n"
				+ "        \"totTodLimit\": \"0\",\r\n"
				+ "        \"totLimitAmount\": \"0\",\r\n"
				+ "        \"turnovers\": {\r\n"
				+ "            \"acyMtdToverDr\": \"7446972.3\",\r\n"
				+ "            \"lcyMtdToverDr\": \"7446972.3\",\r\n"
				+ "            \"acyMtdToverCr\": \"8077828.17\",\r\n"
				+ "            \"lcyMtdToverCr\": \"8077828.17\",\r\n"
				+ "            \"acyTov\": \"AED\",\r\n"
				+ "            \"lcyTov\": \"AED\"\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    \"accSvcacsig\": {\r\n"
				+ "        \"accsigdetails\": [\r\n"
				+ "            {\r\n"
				+ "                \"sigId\": \"00000001\",\r\n"
				+ "                \"sigType\": \"NORMAL\",\r\n"
				+ "                \"approvLimit\": \"0\",\r\n"
				+ "                \"sigName\": \"TEST_CUSTOMER_00000001\",\r\n"
				+ "                \"sigMsg\": \"Group:   | Co-signee: N  | Reference1: 27-02-2012  | Reference2: \",\r\n"
				+ "                \"soloSig\": \"1\",\r\n"
				+ "                \"cifId\": \"010022848\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"accMsg\": \"* Signature Authorization Instructions: Payments *\\n\\nOperating Instruction |      Limit From       |      Limit To         |      Cond On         |  Condition\\n-----------------------------------------------------------------------------------------------------------------------------\\nSingle                |                  0.00 |             Unlimited | Sign                 | 00000001                                                                                                                                                                                                                                                         \\n\\n\\nSignature Group | Signature ID\\n----------------------------------------\\n\\n* ALL OTHER INSTRUCTIONS AND MANDATE BELOW *\\n\\n\\nCHANGED SIGNATURE AS OF 27-02-2012\\n\\n\\n\\nMODIFIED THE A/C BASED ON MASHREQ SIGNATURE CHANGE FORM DATED: 16-02-2012 AS OF 27-02-2012\"\r\n"
				+ "    },\r\n"
				+ "    \"compliance\": [\r\n"
				+ "        {\r\n"
				+ "            \"reasonCode\": \"KYCEXP\",\r\n"
				+ "            \"applicableDate\": \"2021-11-10\",\r\n"
				+ "            \"expired\": \"N\",\r\n"
				+ "            \"reasonDescription\": \"KYC Expiry\"\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"custAcc\": {\r\n"
				+ "        \"branch\": \"017\",\r\n"
				+ "        \"account\": \"010693206884\",\r\n"
				+ "        \"misDetails\": {\r\n"
				+ "            \"refrtType\": \"X\",\r\n"
				+ "            \"calcmeth\": \"1\",\r\n"
				+ "            \"txnMis2\": \"PRDCUGOLD\",\r\n"
				+ "            \"compMis1\": \"RBG\",\r\n"
				+ "            \"compMis2\": \"CSS0010\",\r\n"
				+ "            \"compMis3\": \"SCH0001\",\r\n"
				+ "            \"compMis4\": \"A3\",\r\n"
				+ "            \"misAccLog\": [\r\n"
				+ "                {\r\n"
				+ "                    \"misCls\": \"CUST_SGMT\",\r\n"
				+ "                    \"txnDate\": \"2023-01-09\",\r\n"
				+ "                    \"oldMiscd\": \"CSS0010\",\r\n"
				+ "                    \"newMiscd\": \"CSS0077\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    \"jointHolders\": [],\r\n"
				+ "    \"udfDetails\": [\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ACC_CLOSURE_REASON\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"APPROVER_CODES\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"APP_EXPECTED_LOSS_ACC\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"APP_EXPL\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ATM_CARD_DELIVERY_CHANNEL\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BEH_SCORE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"BENEFIT_TYPE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CAMPAIGN_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CAMPAIGN_CODE_ACC\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CHANNEL\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"CHANNEL_ACC\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"DELIVERY_CODE_ACC\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"DEVIATION_CODE_01\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"DEVIATION_CODE_02\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"DEVIATION_CODE_03\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"DEVIATION_CODE_04\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"DEVIATION_CODE_05\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"DOWNGRADE_ATT_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"DTCUST\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"DTNFL_CASA\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"DUNN_HISTORY_ACC\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"E-STATEMENT_REQD\",\r\n"
				+ "            \"fieldValue\": \"Yes\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ELCM_EL_ACC\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ELCM_LGD_ACC\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ELCM_PD_ACC\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ESTMT_ALERT_FLAG\",\r\n"
				+ "            \"fieldValue\": \"No\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"FAC_RESTRUCTURE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"FAX_INDEMNITY_FLAG\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"FAX_STATEMENT\",\r\n"
				+ "            \"fieldValue\": \"No\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"FIFA_CARD\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"FP_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"FX_DEAL_INDM_FLAG\",\r\n"
				+ "            \"fieldValue\": \"N\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"INDUSTRY_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"INSTRUCTION_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"INS_CODE\",\r\n"
				+ "            \"fieldValue\": \"9\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"LEASE_RENTAL_FINANCING\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"LIFE_INSURANCE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"LOBCODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"MERCHANT_ACC\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"MIN_OD_CLNUP_PERIOD\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"MT5_ID\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"NON_REFERRAL\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"NOON_EMAIL_ID\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"NOON_ID\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"OD_CLNUP_FREQUENCY\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"ONLINE_BANKING\",\r\n"
				+ "            \"fieldValue\": \"Y\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PARTNER_NAME\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PARTNER_UNIQUE_ID\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PIN_DELIVERY_CHANNEL\",\r\n"
				+ "            \"fieldValue\": \"B\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PORTFOLIO_MANAGER\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PROJECT_NAME\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PROPERTY_ADDRESS\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PROPERTY_VAL\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"PURPOSE_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"REFERRER\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"RENEWAL_DATE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"SECTOR_CODE\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"SELLER\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"SELLER_ACC\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"SELLER_ID\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"fieldName\": \"TLM_NRS_FLAG\"\r\n"
				+ "        }\r\n"
				+ "    ]\r\n"
				+ "}";
		return json;
	}
	

}
